version: '3.8'

services:
  db:
    image: postgres:15
    container_name: job_recommendation_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: roo
      POSTGRES_DB: uvivio_db
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: job_recommendation_service
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5433
      DB_DATABASE: uvivio_db
      DB_USERNAME: root
      DB_PASSWORD: root
      PORT: 5000
      JWT_SECRET: your_jwt_secret_key
      groq: your_groq_api_key
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]

volumes:
  postgres_data:
